#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileDB.Android.Test.Resource", IsApplication=true)]

namespace MobileDB.Android.Test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::MobileDB.Android.Test.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::MobileDB.Android.Test.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::MobileDB.Android.Test.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::MobileDB.Android.Test.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::MobileDB.Android.Test.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::MobileDB.Android.Test.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::MobileDB.Android.Test.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::MobileDB.Android.Test.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::MobileDB.Android.Test.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::MobileDB.Android.Test.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::MobileDB.Android.Test.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::MobileDB.Android.Test.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::MobileDB.Android.Test.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::MobileDB.Android.Test.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::MobileDB.Android.Test.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::MobileDB.Android.Test.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::MobileDB.Android.Test.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::MobileDB.Android.Test.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::MobileDB.Android.Test.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::MobileDB.Android.Test.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::MobileDB.Android.Test.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::MobileDB.Android.Test.Resource.Layout.test_suite;
			global::Xunit.Runners.Resource.Drawable.dialog_disclosure = global::MobileDB.Android.Test.Resource.Drawable.dialog_disclosure;
			global::Xunit.Runners.Resource.Drawable.dialog_expander_ic_minimized = global::MobileDB.Android.Test.Resource.Drawable.dialog_expander_ic_minimized;
			global::Xunit.Runners.Resource.Id.dialog_BoolField = global::MobileDB.Android.Test.Resource.Id.dialog_BoolField;
			global::Xunit.Runners.Resource.Id.dialog_Button = global::MobileDB.Android.Test.Resource.Id.dialog_Button;
			global::Xunit.Runners.Resource.Id.dialog_DisclosureField = global::MobileDB.Android.Test.Resource.Id.dialog_DisclosureField;
			global::Xunit.Runners.Resource.Id.dialog_ImageLeft = global::MobileDB.Android.Test.Resource.Id.dialog_ImageLeft;
			global::Xunit.Runners.Resource.Id.dialog_ImageRight = global::MobileDB.Android.Test.Resource.Id.dialog_ImageRight;
			global::Xunit.Runners.Resource.Id.dialog_LabelField = global::MobileDB.Android.Test.Resource.Id.dialog_LabelField;
			global::Xunit.Runners.Resource.Id.dialog_LabelSubtextField = global::MobileDB.Android.Test.Resource.Id.dialog_LabelSubtextField;
			global::Xunit.Runners.Resource.Id.dialog_Panel = global::MobileDB.Android.Test.Resource.Id.dialog_Panel;
			global::Xunit.Runners.Resource.Id.dialog_RadioButtonList = global::MobileDB.Android.Test.Resource.Id.dialog_RadioButtonList;
			global::Xunit.Runners.Resource.Id.dialog_SliderField = global::MobileDB.Android.Test.Resource.Id.dialog_SliderField;
			global::Xunit.Runners.Resource.Id.dialog_Spinner = global::MobileDB.Android.Test.Resource.Id.dialog_Spinner;
			global::Xunit.Runners.Resource.Id.dialog_ValueField = global::MobileDB.Android.Test.Resource.Id.dialog_ValueField;
			global::Xunit.Runners.Resource.Id.iFormFieldValue = global::MobileDB.Android.Test.Resource.Id.iFormFieldValue;
			global::Xunit.Runners.Resource.Layout.dialog_achievements = global::MobileDB.Android.Test.Resource.Layout.dialog_achievements;
			global::Xunit.Runners.Resource.Layout.dialog_boolfieldleft = global::MobileDB.Android.Test.Resource.Layout.dialog_boolfieldleft;
			global::Xunit.Runners.Resource.Layout.dialog_boolfieldright = global::MobileDB.Android.Test.Resource.Layout.dialog_boolfieldright;
			global::Xunit.Runners.Resource.Layout.dialog_boolfieldsubleft = global::MobileDB.Android.Test.Resource.Layout.dialog_boolfieldsubleft;
			global::Xunit.Runners.Resource.Layout.dialog_boolfieldsubright = global::MobileDB.Android.Test.Resource.Layout.dialog_boolfieldsubright;
			global::Xunit.Runners.Resource.Layout.dialog_button = global::MobileDB.Android.Test.Resource.Layout.dialog_button;
			global::Xunit.Runners.Resource.Layout.dialog_datefield = global::MobileDB.Android.Test.Resource.Layout.dialog_datefield;
			global::Xunit.Runners.Resource.Layout.dialog_fieldsetlabel = global::MobileDB.Android.Test.Resource.Layout.dialog_fieldsetlabel;
			global::Xunit.Runners.Resource.Layout.dialog_floatimage = global::MobileDB.Android.Test.Resource.Layout.dialog_floatimage;
			global::Xunit.Runners.Resource.Layout.dialog_labelfieldbelow = global::MobileDB.Android.Test.Resource.Layout.dialog_labelfieldbelow;
			global::Xunit.Runners.Resource.Layout.dialog_labelfieldright = global::MobileDB.Android.Test.Resource.Layout.dialog_labelfieldright;
			global::Xunit.Runners.Resource.Layout.dialog_onofffieldright = global::MobileDB.Android.Test.Resource.Layout.dialog_onofffieldright;
			global::Xunit.Runners.Resource.Layout.dialog_panel = global::MobileDB.Android.Test.Resource.Layout.dialog_panel;
			global::Xunit.Runners.Resource.Layout.dialog_root = global::MobileDB.Android.Test.Resource.Layout.dialog_root;
			global::Xunit.Runners.Resource.Layout.dialog_selectlist = global::MobileDB.Android.Test.Resource.Layout.dialog_selectlist;
			global::Xunit.Runners.Resource.Layout.dialog_selectlistfield = global::MobileDB.Android.Test.Resource.Layout.dialog_selectlistfield;
			global::Xunit.Runners.Resource.Layout.dialog_textarea = global::MobileDB.Android.Test.Resource.Layout.dialog_textarea;
			global::Xunit.Runners.Resource.Layout.dialog_textfieldbelow = global::MobileDB.Android.Test.Resource.Layout.dialog_textfieldbelow;
			global::Xunit.Runners.Resource.Layout.dialog_textfieldright = global::MobileDB.Android.Test.Resource.Layout.dialog_textfieldright;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000e
			public const int OptionHostName = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int OptionPort = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int OptionRemoteServer = 2131099661;
			
			// aapt resource value: 0x7f06001d
			public const int OptionsButton = 2131099677;
			
			// aapt resource value: 0x7f060018
			public const int ResultFullName = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int ResultMessage = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int ResultResultState = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int ResultRunSingleMethodTest = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int ResultStackTrace = 2131099675;
			
			// aapt resource value: 0x7f060013
			public const int ResultsFailed = 2131099667;
			
			// aapt resource value: 0x7f060010
			public const int ResultsId = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int ResultsIgnored = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int ResultsInconclusive = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int ResultsMessage = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int ResultsPassed = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int ResultsResult = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int RunTestsButton = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int TestSuiteListView = 2131099678;
			
			// aapt resource value: 0x7f060002
			public const int dialog_BoolField = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int dialog_Button = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int dialog_DisclosureField = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int dialog_ImageLeft = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int dialog_ImageRight = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int dialog_LabelField = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int dialog_LabelSubtextField = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int dialog_Panel = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int dialog_RadioButtonList = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int dialog_SliderField = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int dialog_Spinner = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int dialog_ValueField = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int iFormFieldValue = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_boolfieldleft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_boolfieldright = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_boolfieldsubleft = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_boolfieldsubright = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_datefield = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_fieldsetlabel = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_floatimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_labelfieldbelow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_labelfieldright = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_onofffieldright = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_panel = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_root = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_selectlist = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_selectlistfield = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_textarea = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_textfieldbelow = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_textfieldright = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int options = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int results = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int test_result = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int test_suite = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
